# Generated by Django 4.2.6 on 2023-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='task',
            name='material',
            field=models.CharField(default='fff', max_length=100, verbose_name='Материал'),
        ),
    ]
